name = "worldview"
compatibility_date = "2026-06-11"
account_id = "939a7fa8a072b9ac7f9c41885fe71380"

routes = [
  { pattern = "worldview.dhanjit.me", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
